export const LATEX_SYMBOLS: Record<string, string> = {
  alpha: 'α',
  beta: 'β',
  gamma: 'γ',
  delta: 'δ',
  epsilon: 'ε',
  zeta: 'ζ',
  eta: 'η',
  theta: 'θ',
  iota: 'ι',
  kappa: 'κ',
  lambda: 'λ',
  mu: 'μ',
  nu: 'ν',
  xi: 'ξ',
  omicron: 'ο',
  pi: 'π',
  rho: 'ρ',
  sigma: 'σ',
  tau: 'τ',
  upsilon: 'υ',
  phi: 'φ',
  chi: 'χ',
  psi: 'ψ',
  omega: 'ω',
  Gamma: 'Γ',
  Delta: 'Δ',
  Theta: 'Θ',
  Lambda: 'Λ',
  Xi: 'Ξ',
  Pi: 'Π',
  Rho: 'Ρ',
  Sigma: 'Σ',
  Tau: 'Τ',
  Upsilon: 'Υ',
  Phi: 'Φ',
  Chi: 'Χ',
  Psi: 'Ψ',
  Omega: 'Ω',
  leq: '≤',
  geq: '≥',
  neq: '≠',
  approx: '≈',
  infty: '∞',
  cdot: '·',
  times: '×',
  div: '÷',
  pm: '±',
  mp: '∓',
  forall: '∀',
  partial: '∂',
  exists: '∃',
  nexists: '∄',
  in: '∈',
  ni: '∋',
  cup: '∪',
  cap: '∩',
  varnothing: '∅',
  ast: '∗',
  therefore: '∴',
  because: '∵',
  gets: '←',
  to: '→',
  uparrow: '↑',
  downarrow: '↓',
  leftrightarrow: '↔',
  updownarrow: '↕',
  Leftarrow: '⇐',
  Rightarrow: '⇒',
  Leftrightarrow: '⇔',
  longleftarrow: '⟵',
  longrightarrow: '⟶',
  longleftrightarrow: '⟷',
  int: '∫',
  iint: '∬',
  iiint: '∭',
  sum: '∑',
  prod: '∏',
  sin: 'sin',
  cos: 'cos',
  tan: 'tan',
  csc: 'csc',
  sec: 'sec',
  cot: 'cot',
};

export const SYMBOL_TO_LATEX = Object.entries(LATEX_SYMBOLS).reduce<Record<string, string>>(
  (result, [command, symbol]) => {
    if (!(symbol in result)) {
      result[symbol] = command;
    }
    return result;
  },
  {},
);
